### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/social-cards#2]
# Create basic structure of card

## Tasks

- [x] Include hardcoded user name
- [x] Include hardcoded dummy text
- [x] Add like icon with dummy count number
