### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/social-cards#6]
# Style site

## Tasks

- [ ] Add global css
- [ ] Make sure all spacings are constant, eg, space below h1's p's etc
- [ ] Make sure enough white space
- [ ] Consistant colour scheme
- [ ] Add font/s
