### ISSUE TITLE
Initial landing page

### ISSUE THREAD

**Issue by mjjstockman** [mjjstockman/social-cards#9]
# Home Page

## Tasks

- [ ] Remove unwanted boiler template parts
- [ ] Add basic structure of home page
- [ ] Make sure semantic elements are used eg, main, header, footer, sections
